ALTER SESSION SET "_oracle_script" = true;

CREATE USER HR IDENTIFIED BY HR;

ALTER USER HR DEFAULT TABLESPACE USERS
              QUOTA UNLIMITED ON USERS;

ALTER USER HR TEMPORARY TABLESPACE TEMP;

GRANT CREATE SESSION, CREATE VIEW, ALTER SESSION, CREATE SEQUENCE TO HR;
GRANT CREATE SYNONYM, CREATE DATABASE LINK, RESOURCE TO HR;